// Generated by https://quicktype.io

export interface Episode {
  /* Temporary id */
  id: string;
  name: string;
  externalUrls: string[];
  severity: string;
  startedAt: string;
  endedAt: string;
  updatedAt: string;
  geojson: GeoJSON.FeatureCollection;
  location: string;
  forecasted: boolean;
}
