import ReactMarkdown from 'react-markdown';
import gfm from 'remark-gfm';
import { Article } from '~components/Layout';

const md = `# Cookie files policy and operational data
| Name                      | Domain            | Description                                                                                                                                                                                                                 | Duration                   | Type          |
| ------------------------- | ----------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------- | ------------- |
| AnalyticsSyncHistory      | .linkedin.com     | Used to store information about the time of a successful sync using the lms_analytics cookie                                                                                                                                | 30 days                    | Other         |
| UserMatchHistory          | .linkedin.com     | Used in the identity synchronization process. Stores the latest sync time so you don't have to repeat this process too often                                                                                                | 30 days                    | Other         |
| \_fbp                     | .disaster.ninja   | Used by Facebook to deliver advertising. The cookie contains an encrypted Facebook user ID and browser ID. It will receive information from this website to better target and optimise advertising.                         | 90 days                    | Advertisement |
| \_fbp                     | .kontur.io        | Used by Facebook to deliver advertising. The cookie contains an encrypted Facebook user ID and browser ID. It will receive information from this website to better target and optimise advertising.                         | 81 day                     | Advertisement |
| \_ga                      | .kontur.io        | Сalculates visitor, session and campaign data and also keeps track of site usage for the site's analytics report. Also stores information anonymously and assigns a randomly generated number to recognize unique visitors. | 391 day, 50 min            | Analytics     |
| \_ga                      | .disaster.ninja   | Calculates visitor, session and campaign data and also keeps track of site usage for the site's analytics report. Also stores information anonymously and assigns a randomly generated number to recognize unique visitors. | 400 days                   | Analytics     |
| \_gid                     | .kontur.io        | Registers a unique ID that is used to generate statistical data on how the visitor uses the website.                                                                                                                        |                            | Analytics     |
| \_gid                     | .disaster.ninja   | Registers a unique ID that is used to generate statistical data on how the visitor uses the website.                                                                                                                        | 24 hour                    | Analytics     |
| \_yasc                    | .yandex.ru        | Collecting data about the user's interests and displaying relevant advertising on other sites.                                                                                                                              | 385 days, 10 hours, 21 min | Advertisement |
| \_ym_d                    | .yandex.ru        | Yandex sets this cookie to store the date of the users first site session.                                                                                                                                                  | 349 days, 7 hours, 49 min  | Analytics     |
| \_ym_d                    | .kontur.io        | Yandex sets this cookie to store the date of the users first site session.                                                                                                                                                  | 317 days, 23 hours, 36 min | Analytics     |
| \_ym_d                    | .disaster.ninja   | Yandex sets this cookie to store the date of the users first site session.                                                                                                                                                  | 315 days, 23 hours, 56 min | Analytics     |
| \_ym_isad                 | .kontur.io        | Yandex sets this cookie to determine if a visitor has ad blockers                                                                                                                                                           |                            | Analytics     |
| \_ym_isad                 | .disaster.ninja   | Yandex sets this cookie to determine if a visitor has ad blockers                                                                                                                                                           | 20 hours                   | Analytics     |
| \_ym_uid                  | .kontur.io        | Yandex sets this cookie to identify site users.                                                                                                                                                                             | 317 days, 23 hours, 36 min | Analytics     |
| ym_uid                    | .yandex.ru        | Yandex sets this cookie to identify site users                                                                                                                                                                              | 349 days, 7 hours, 49 min  | Analytics     |
| ym_uid                    | .disaster.ninja   | Yandex sets this cookie to identify site users                                                                                                                                                                              | 315 days, 23 hours, 56 min | Analytics     |
| \_ym_visorc               | .disaster.ninja   | Allow the site's Session Replay to function correctly                                                                                                                                                                       | 30 min                     | Performance   |
| bcookie                   | .linkedin.com     | Browser ID cookie to uniquely identify devices accessing LinkedIn for platform abuse detection                                                                                                                              | 310 days, 2 hours          | Functional    |
| fr                        | .facebook.com     | Used to deliver, measure and improve the relevancy of ads                                                                                                                                                                   | 35 days, 22 hours          | Performance   |
| gdpr                      | .yandex.ru        | Determines whether the visitor has accepted the cookie consent box. This ensures that the cookie consent box will not be presented again upon re-entry.                                                                     | Session                    | Functional    |
| i                         | .yandex.ru        | This cookie is set by OpenX to record anonymized user data, such as IP address, geographical location, websites visited, ads clicked by the user etc., for relevant advertising.                                            | 345 days, 2 hours          | Analytics     |
| intercom-id-e59cl64z      | .kontur.io        | Anonymous visitor identifier cookie. As people visit your site they get this cookie                                                                                                                                         | 261 day, 23 min            | Other         |
| intercom-id-e59cl64z      | .disaster.ninja   | Anonymous visitor identifier cookie. As people visit your site they get this cookie                                                                                                                                         | 248 days, 20 hours, 48 min | Other         |
| intercom-session-e59cl64z | .kontur.io        | Identifier for each unique browser session. This session cookie is refreshed on each successful logged-in ping, extending it one week from that moment.                                                                     | 7 days                     | Other         |
| intercom-session-e59cl64z | .disaster.ninja   | Identifier for each unique browser session. This session cookie is refreshed on each successful logged-in ping, extending it one week from that moment.                                                                     | 7 days                     | Other         |
| is_gdpr                   | .yandex.ru        |                                                                                                                                                                                                                             | 379 days, 19 hours, 47 min | Analytics     |
| is_gdpr_b                 | .yandex.ru        |                                                                                                                                                                                                                             | 379 days, 19 hours, 47 min | Analytics     |
| lang                      | .ads.linkedin.com | Used to remember the user's language settings so that LinkedIn.com appears in the language selected by the user in their settings.                                                                                          | session                    | Functional    |
| lang                      | .linkedin.com     | Used to remember the user's language settings so that LinkedIn.com appears in the language selected by the user in their settings.                                                                                          | session                    | Functional    |
| li_sugr                   | .linkedin.com     | Used to to store browser details                                                                                                                                                                                            | 90 days                    | Analytics     |
| lidc                      | .linkedin.com     | Used to simplify data center selection                                                                                                                                                                                      | 24 hours                   | Functional    |
| ln_or                     | .disaster.ninja   | Registers statistical data on users' behaviour on the website. Used for internal analytics by the website operator.                                                                                                         | 24 hours                   | Analytics     |
| muc_ads                   | .t.co             | Advertising cookie                                                                                                                                                                                                          | 345 days, 2 hours, 30 min  | Advertisement |
| personalization_id        | .twitter.com      | Advertising cookie                                                                                                                                                                                                          | 345 days, 2 hours, 30 min  | Advertisement |
| yabs-sid                  | mc.yandex.ru      | Yandex sets this cookie to store the session ID                                                                                                                                                                             | session                    | Analytics     |
| yandexuid                 | .yandex.ru        | Allow to use additional features of the website and customize it according to users preferences                                                                                                                             | 345 days, 2 hours, 30 min  | Analytics     |
| yandexuid                 | .webvisor.org     | Allow to use additional features of the website and customize it according to users preferences                                                                                                                             | 400 days                   | Analytics     |
| ymex                      | .yandex.ru        | Used to collect data about the user's interests and display relevant advertising for users on other sites                                                                                                                   | 310 days, 2 hours, 30 min  | Performance   |
| ys                        | .yandex.ru        |                                                                                                                                                                                                                             | session                    |               |
| yuidss                    | .yandex.ru        | Yandex stores this cookie in the user's browser in order to recognize the visitor.                                                                                                                                          | 345 days, 2 hours          | Performance   |
`;
export function CookiesPage() {
  return (
    <Article>
      <ReactMarkdown remarkPlugins={[gfm]}>{md}</ReactMarkdown>
    </Article>
  );
}
