export const acapsSampleData = [
  // risk list
  {
    iso3: ['BRA'],
    impact: '3',
    status: 'Materialised',
    comment:
      'Brazil’s government agencies warned of droughts this week as the country faces its worst dry spell in 91 years, increasing fears of energy rationing, hitting hydroelectric power generation and agriculture while raising the risk of Amazon fires. several states could be affected: Minas Gerais, Goiás, Mato Grosso do Sul, São Paulo and Paraná. The alert pointed out that studies carried out by the Brazilian SNM foresee this tendency for the period June-July-August/2021.\n -   Unforeseen heavy rains continue to cause flooding in northeast and southern Brazil\n- Droughts in central and southern Brazil, because extension of La Niña period\n- Continued mobility limitations due to road destruction\n',
    country: ['Brazil', 'Venezuela'],
    adm1_eng_name: ['Adm 1', 'Adm 2'],
    trigger:
      '-   Unforeseen heavy rains continue to cause flooding in northeast and southern Brazil\n- Droughts in central and southern Brazil, because extension of La Niña period\n- Continued mobility limitations due to road destruction\n',
    exposure: '250,000-500,000',
    crisis_id: ['BRA003'],
    indicator: ["Brazil's northeastern, southern, and central regions face flood risks."],
    intensity: '3',
    rationale:
      'Brazil’s government agencies warned of droughts this week as the country faces its worst dry spell in 91 years, increasing fears of energy rationing, hitting hydroelectric power generation and agriculture while raising the risk of Amazon fires. several states could be affected: Minas Gerais, Goiás, Mato Grosso do Sul, São Paulo and Paraná. The alert pointed out that studies carried out by the Brazilian SNM foresee this tendency for the period June-July-August/2021.\n',
    risk_type: 'Marked deterioration in an existing crisis',
    source_id: 'R0139',
    risk_level: 'High',
    countrywide: false,
    probability: 'High',
    source_date: '2021-06-02',
    source_name: 'ACAPS',
    vulnerability:
      'The impact in terms of humanitarian consequences focuses on a significant reduction in food consumption, which means increased levels of malnutrition for vulnerable groups. This encourages an increase in negative coping strategies (indebtedness, skipping meals, reduced dietary variety, etc.). This situation may be exacerbated by socio-political instability, which could increase due to the presidential elections projected for October 2022. ',
    geographic_level: 'Subnational',
    last_risk_update: '2024-06-13T13:54:05.000Z',
    acaps_source_dataset: 'Risk list',
    isRiskList: true,
    _internal_filter_date: '2024-06-13',
    source_link:
      'https://www.acaps.org/special-report/crisisinsight-global-risk-analysis-3',
  },
  // seasonal events
  {
    adm1: 'PAN.1_1, PAN.2_1, PAN.3_1, PAN.4_1, PAN.5_1, PAN.6_1, PAN.7_1, PAN.8_1, PAN.9_1, PAN.10_1, PAN.12_1, PAN.11_1, PAN.13_1',
    iso3: ['PAN'],
    label: ['Rainy season'],
    months: [
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    comment: 'Rainy season',
    country: ['Panama'],
    indicator: ['Main wet/ Rainy/ Monsoon season', 'Indicator part 2'],
    subindicator: ['Subindicator part 1', 'Subindicator part 2'],
    source_id: '339',
    event_type: ['Seasonal hazard'],
    countrywide: true,
    source_date: '2011-04-01',
    source_link:
      'https://climateknowledgeportal.worldbank.org/sites/default/files/2018-10/wb_gfdrr_climate_change_country_profile_for_PAN.pdf',
    source_name: 'World Bank',
    acaps_source_dataset: 'Seasonal events calendar',
    isSeasonalEvents: true,
    _internal_filter_date: '2011-04-01',
  },
  // info landscape
  {
    iso3: ['COL'],
    comment:
      'Flooding caused by La Niña and heavy rain falls in Caribbean, Northern Pacific region, North and Central Andean regions and Central-Western region. Major rivers continue to rise. ',
    country: ['Colombia', 'Chile'],
    created: '2022-06-17',
    indicator: ['ILI2 - Access to information', 'ILI3 - Access to more information'],
    source_id: 'I00002',
    entry_type: 'Event',
    countrywide: true,
    source_date: '2021-11-01',
    source_link: 'DREF Final Report Colombia: La Niña phenomenon (Floods)',
    source_name: 'IFRC',
    subindicator: ['ILS2.1 - Telecommunications infrastructures damage or limitations'],
    acaps_source_dataset: 'Information landscape dataset',
    isInformationLandscape: true,
    _internal_filter_date: '2021-11-01',
  },
  // protection risk monitor
  {
    adm1: 'VEN.1_1, VEN.2_1, VEN.3_1, VEN.4_1, VEN.5_1, VEN.6_1, VEN.7_1, VEN.8_1, VEN.9_1, VEN.10_1, VEN.11_1, VEN.12_1, VEN.13_1, VEN.14_1, VEN.15_1, VEN.16_1, VEN.17_1, VEN.18_1, VEN.19_1, VEN.20_1, VEN.21_1, VEN.22_1, VEN.23_1, VEN.24_1, VEN.25_1',
    iso3: ['VEN'],
    comment:
      'According Global Centre for Responsability to Project: The Venezuelan government is pursuing policies that enable systematic human rights violations and abuses in an apparent attempt to silence dissent. Extrajudicial killings appear to be part of a systematic strategy to reinforce social control. The number of killings reduced following the publication of the FFM’s first report in September 2020, suggesting a possible deterrent effect of international scrutiny. However, state security forces have continued their targeted repression and systematic abuses. Government-linked media outlets play a key role in state repression and persecution. ',
    country: ['Venezuela'],
    source_id: 'P00541',
    countrywide: true,
    source_date: '2022-09-01',
    source_link: 'https://www.globalr2p.org/countries/venezuela/',
    additional_sources:
      'https://www.expedientepublico.org/asi-fue-el-allanamiento-contra-el-periodico-de-guatemala-la-trama-por-silenciar-a-quienes-denuncian-la-corrupcion/',
    source_name: 'Global2p',
    adm1_eng_name: [
      'Amazonas',
      'Anzoátegui',
      'Apure',
      'Aragua',
      'Barinas',
      'Bolívar',
      'Carabobo',
      'Cojedes',
      'Delta Amacuro',
      'Dependencias Federales',
      'Distrito Capital',
      'Falcón',
      'Guárico',
      'Lara',
      'Mérida',
      'Miranda',
      'Monagas',
      'Nueva Esparta',
      'Portuguesa',
      'Sucre',
      'Táchira',
      'Trujillo',
      'Vargas',
      'Yaracuy',
      'Zulia',
    ],
    protection_risk: [
      'R02 - Attacks on civilians and other unlawful killings, and attacks on civilian objects',
    ],
    acaps_source_dataset: 'Protection risks monitor',
    isProtectionRisks: true,
    _internal_filter_date: '2022-09-01',
    targeting_specific_population_groups: ['Political affilitation'],
  },
];
