export const hotData = [
  {
    teams: [],
    author: 'naveenpf',
    k_type: 'polygon',
    aoiBBOX: [75.956806, 10.176628, 76.874643, 10.774978],
    created: '2018-11-20T17:35:23.715104Z',
    private: false,
    campaigns: [{ id: 261, name: '2018 India Floods' }],
    interests: [{ id: 3, name: 'disaster response' }],
    projectId: 5522,
    countryTag: ['India'],
    difficulty: 'EASY',
    lastUpdated: '2019-11-27T02:54:50.781237Z',
    projectInfo: {
      name: 'India flood mapping',
      locale: 'en',
      description:
        'Monsoon rains have wreaked havoc throughout various states of India, resulting in a number of deaths and huge numbers of displaced citizens. OSM India, supported by HOT, have launched a response to aid relief efforts. This project is to map the buildings.\n\nNote that there may be some buildings already mapped -- please identify buildings that have NOT yet been mapped, and help to improve the quality of the building map edits that have already.',
      instructions:
        '**Imagery Source: Use Maxar Preimum Imagery to map.**\n\nPlease focus on adding only the buildings. Remember to trace the building footprint as accurately as possible - then press the "q" button on your keyboard to square the edges before tagging it as a building.\n\nMany of the tiles will already have buildings mapped -- if you find that the building footprints are not accurate, please correct them if possible.\n\n<h3>Video: Adding Buildings to Openstreetmap</h3>\n<iframe width="560" height="315" src="https://www.youtube.com/embed/E1YJV6I_rhY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>\n\n\n\n\n #### #osm_in #2018IndiaFloods',
      shortDescription: 'Supporting local flood response in India due to monsoons.',
      perTaskInstructions: '',
    },
    mappingTypes: ['ROADS', 'BUILDINGS'],
    organisation: 29,
    activeMappers: 0,
    defaultLocale: 'en',
    percentMapped: 33,
    mappingEditors: ['ID', 'JOSM', 'POTLATCH_2', 'FIELD_PAPERS'],
    projectPriority: 'LOW',
    allowedUsernames: [],
    changesetComment: '#hotosm-project-5522 #osm_in #2018IndiaFloods #mmteamarm',
    organisationLogo:
      'https://cdn.hotosm.org/tasking-manager/uploads/1597218299183_817px-OpenStreetMap-India.svg.png',
    organisationName: 'OSM India',
    organisationSlug: 'osm-india',
    percentValidated: 0,
    taskCreationMode: 'GRID',
    mappingPermission: 'ANY',
    percentBadImagery: 0,
    validationEditors: ['ID', 'JOSM', 'POTLATCH_2', 'FIELD_PAPERS'],
    validationPermission: 'ANY',
  },
  {
    teams: [],
    author: 'naveenpf',
    k_type: 'polygon',
    aoiBBOX: [75.956806, 10.176628, 76.874643, 10.774978],
    created: '2018-11-16T08:00:28.447658Z',
    private: false,
    campaigns: [{ id: 261, name: '2018 India Floods' }],
    interests: [{ id: 3, name: 'disaster response' }],
    projectId: 5496,
    countryTag: ['India'],
    difficulty: 'EASY',
    lastUpdated: '2020-11-14T21:19:03.811366Z',
    projectInfo: {
      name: 'Thrissur, Kerala Floods, India Road Network Improvement',
      locale: 'en',
      description:
        '`You could join HOTOSM local slack #disaster channel while mapping these tasks` (https://slack.hotosm.org)\n\nMapping project in response to 2018 Flooding in Kerala\nThrissur , Kerala, India Road Network Improvement',
      instructions:
        'Please focus on adding only the missing roads which are OSM highway=unclassified tagged.\n\n[The India Highway Tagging Guide](https://wiki.openstreetmap.org/wiki/India:Tags/Highway) has more information on properly classifying roads in India\n\n<h3>Video: Adding roads to Openstreetmap</h3>\n<iframe width="560" height="315" src="https://www.youtube.com/embed/ZBLwb2nisJQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>\n\nRoads Improvement Project Specific Instructions\n================================\n* The most recent imagery is DG Premium, be aware, DG Premium to zoom level 17 is newest, switches to older imagery zoomed past 17\n* Please add missing roads. Most will be "unclassified"\n\n #### #osm_in #2018IndiaFloods',
      shortDescription:
        'You can join HOTOSM local slack #disaster channel while mapping these tasks` (https://slack.hotosm.org)\n\nMapping project in response to 2018 Flooding in Kerala',
      perTaskInstructions: '',
    },
    mappingTypes: ['ROADS'],
    organisation: 29,
    activeMappers: 0,
    defaultLocale: 'en',
    percentMapped: 98,
    mappingEditors: ['ID', 'JOSM', 'POTLATCH_2', 'FIELD_PAPERS'],
    projectPriority: 'HIGH',
    allowedUsernames: [],
    changesetComment: '#hotosm-project-5496 #osm_in #2018IndiaFloods',
    organisationLogo:
      'https://cdn.hotosm.org/tasking-manager/uploads/1597218299183_817px-OpenStreetMap-India.svg.png',
    organisationName: 'OSM India',
    organisationSlug: 'osm-india',
    percentValidated: 33,
    taskCreationMode: 'GRID',
    mappingPermission: 'ANY',
    percentBadImagery: 0,
    validationEditors: ['ID', 'JOSM', 'POTLATCH_2', 'FIELD_PAPERS'],
    validationPermission: 'ANY',
  },
  {
    teams: [],
    status: 'ARCHIVED',
    isArchived: true,
    author: 'geohacker',
    k_type: 'polygon',
    aoiBBOX: [76.959254, 10.048946, 77.140251, 10.312653],
    created: '2020-08-10T05:25:03.149752Z',
    private: false,
    campaigns: [],
    interests: [
      {
        id: 3,
        name: 'disaster response',
      },
      {
        id: 6,
        name: 'disaster preparedness',
      },
    ],
    projectId: 9165,
    countryTag: ['India'],
    difficulty: 'MODERATE',
    lastUpdated: '2023-07-08T15:10:18.497268Z',
    projectInfo: {
      name: 'Munnar, Kerala - Landslide 2020 - Roads',
      locale: 'en',
      description:
        'Over the last couple of years, the Monsoons have been causing unprecedented havoc through floods and landslides in the Kerala state. [In 2018](https://en.wikipedia.org/wiki/2018_Kerala_floods), Kerala saw the most devastating crises with 683 deaths and 140 people missing. With many parts of the state under red alert, more rains and flood is predicted. \n\nThis year, the community is coming together early to prepare. Currently the focus is Munnar, Kerala. The goal of this task is to map roads.\n\nIf you have questions about this task, join the [OSM Kerala Telegram Channel](https://t.me/osmkerala)',
      instructions:
        '### Imagery\nPlease use **Bing** & **Maxar Imagery** to trace the buildings.\nIf you find a huge offset with the existing data, please do not try to move all the data. See [LearnOSM](https://learnosm.org/en/hot-tips/imagery/)_ for detailed instructions on handling imagery offset, or Aerial Imagery & Alignment for adjusting in the iD editor.\n\n### Roads\n- Two-minute Tutorial: Roads - https://www.youtube.com/watch?v=ZBLwb2nisJQ\n- Map roads and paths that are visible using satellite imagery\n- Do not change alignment or delete existing data\n\n#### Quick tagging guide\n\nType | Tag \n-------|-------\nRoads connecting villages | `highway=unclassified`\nRoads connecting houses, drivable | `highway=residential`\nCongested residential areas, not wide | `highway=living_street`\nTrails covered by foot | `highway=path`\n\nMore detailed guide [is available here.](https://wiki.openstreetmap.org/wiki/India/Tags/Highway#Road_classification_and_tagging_scheme_for_India_.28proposal.29)',
      shortDescription:
        'OpenStreetMap India is mapping Munnar, Kerala which has been seeing higher rates of rainfalls again in 2020. Few days ago, a landslide claimed over 15 lives with more than 40 people still missing.\n\nThis task will focus on mapping roads. If you have questions about this task, join the [OSM Kerala Telegram Channel](https://t.me/osmkerala)',
      perTaskInstructions: '',
    },
    mappingTypes: ['ROADS'],
    organisation: 29,
    activeMappers: 0,
    defaultLocale: 'en',
    percentMapped: 99,
    priorityAreas: [
      {
        type: 'Polygon',
        coordinates: [
          [
            [77.032498, 10.191444],
            [77.070204, 10.196346],
            [77.086805, 10.176506],
            [77.050047, 10.145927],
            [77.02894, 10.130753],
            [77.006648, 10.130753],
            [76.988625, 10.136356],
            [76.972262, 10.154798],
            [76.985779, 10.159233],
            [77.009494, 10.176039],
            [77.013763, 10.181641],
            [77.033921, 10.180007],
            [77.032498, 10.191444],
          ],
        ],
      },
    ],
    mappingEditors: ['ID', 'JOSM', 'POTLATCH_2', 'FIELD_PAPERS', 'CUSTOM'],
    projectPriority: 'LOW',
    allowedUsernames: [],
    changesetComment: '#kerala-floods-2020',
    organisationLogo:
      'https://cdn.hotosm.org/tasking-manager/uploads/1597218299183_817px-OpenStreetMap-India.svg.png',
    organisationName: 'OSM India',
    organisationSlug: 'osm-india',
    percentValidated: 87,
    taskCreationMode: 'GRID',
    mappingPermission: 'ANY',
    percentBadImagery: 0,
    validationEditors: ['ID', 'JOSM', 'POTLATCH_2', 'FIELD_PAPERS', 'CUSTOM'],
    validationPermission: 'ANY',
    enforceRandomTaskSelection: false,
  },
];
