import '@reatom/react/react-dom-batched-updates';
import '@k2-packages/default-theme/variables.css';
import '@k2-packages/default-theme/defaults.css';
import '@k2-packages/default-theme/typography.css';
import '@fortawesome/fontawesome-free/js/fontawesome';
import '@fortawesome/fontawesome-free/js/solid';
import '~core/localization/i18n';
import './global.css';
import './App.tsx';
